import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SoilAi } from "soilai";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Soil App",
  description: "Generated by create soil app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <SoilAi />
      </body>
    </html>
  );
}
